;
; AutoHotkey Version: 1.x
; Language:       English
; Platform:       Win9x/NT
; License:        WTFPL
;
; Script Function:
;	Turns off the monitor
;

#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#NoTrayIcon
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

Sleep, 1000 ; need to wait because otherwise the keyup event generated by calling us (like pressing enter) will bring the monitor back on
SendMessage,0x112,0xF170,2,,Program Manager
Return